### ISSUE TITLE
Live demo

### ISSUE THREAD

**Issue by blondie63** [brizaldi/flutter_project_template_riverpod#1]
Blank page !

**Comment by brizaldi** [comment]
@blondie63 It's because of this [issue](https://github.com/rrousselGit/riverpod/issues/1713) that currently happened on latest riverpod and flutter web, sorry I haven't got time to check any further.

But it should be fine if you run it on other platforms.

**Comment by blondie63** [comment]
@brizaldi I've sent you only as feedback because people clicking on your live demo link see a blank page and they can think that app does'nt works well, maybe it's better you delete this link :)

**Comment by brizaldi** [comment]
Since the riverpod has released a fix, the live demo now works as expected, closing this issue.
